import { apiClient } from "@/lib/api/client";
import type { AddCartItemPayload, Cart } from "@/types/cart";
import type { CouponPreviewResult } from "@/types/coupon";

const IDEMPOTENCY_KEY_HEADER = "Idempotency-Key";

export const cartApi = {
  /** GET /cart — authenticated only; caller must gate this behind auth status. */
  async getCart(signal?: AbortSignal): Promise<Cart> {
    const response = await apiClient.get<Cart>("/cart", { signal });
    return response.data;
  },

  /**
   * POST /cart/items — payload never carries price/productName/userId (the
   * backend rejects unknown fields outright via ValidationPipe's
   * forbidNonWhitelisted). `idempotencyKey` must be generated by the
   * caller once per user intent (see useAddCartItem) and reused verbatim
   * on any retry of that same intent.
   */
  async addItem(payload: AddCartItemPayload, idempotencyKey: string): Promise<Cart> {
    const response = await apiClient.post<Cart>("/cart/items", payload, {
      headers: { [IDEMPOTENCY_KEY_HEADER]: idempotencyKey },
    });
    return response.data;
  },

  /** PATCH /cart/items/:itemId — absolute quantity, not a delta. */
  async updateItemQuantity(itemId: string, quantity: number): Promise<Cart> {
    const response = await apiClient.patch<Cart>(
      `/cart/items/${encodeURIComponent(itemId)}`,
      { quantity },
    );
    return response.data;
  },

  async removeItem(itemId: string): Promise<void> {
    await apiClient.delete(`/cart/items/${encodeURIComponent(itemId)}`);
  },

  /** POST /cart/coupon/preview — never mutates. Payload is only `{code}`. */
  async previewCoupon(code: string): Promise<CouponPreviewResult> {
    const response = await apiClient.post<CouponPreviewResult>(
      "/cart/coupon/preview",
      { code },
    );
    return response.data;
  },

  /** PUT /cart/coupon — applies or replaces. Payload is only `{code}`. */
  async applyCoupon(code: string): Promise<Cart> {
    const response = await apiClient.put<Cart>("/cart/coupon", { code });
    return response.data;
  },

  /** DELETE /cart/coupon — idempotent, no body. */
  async removeCoupon(): Promise<Cart> {
    const response = await apiClient.delete<Cart>("/cart/coupon");
    return response.data;
  },
};
