export const REFRESH_TOKEN_COOKIE = 'refresh_token';

export const EMAIL_VERIFICATION_TOKEN_TTL_MS = 24 * 60 * 60 * 1000;
export const EMAIL_VERIFICATION_TOKEN_TTL_HOURS = 24;

export const PASSWORD_RESET_TOKEN_TTL_MS = 60 * 60 * 1000;
export const PASSWORD_RESET_TOKEN_TTL_MINUTES = 60;
